name: Build and create release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Checkout speedcubingLib
        uses: actions/checkout@v4

      - name: Build speedcubingLib
        run: |
          mvn -B package --file pom.xml


      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: speedcubingLib
          path: /target/speedcubingLib-1.0-SNAPSHOT.jar


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Tag Name
        run: |
          TAG_NAME=$(echo "${GITHUB_REF}" | sed 's|refs/tags/||')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          prerelease: true
          body: |
                Release ${{ github.ref }}
                This is an auto-generated release.
        

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/speedcubingLib-1.0-SNAPSHOT.jar
          asset_name: speedcubingLib-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
