name: Build and create release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Checkout speedcubingLib
        uses: actions/checkout@v4

      - name: Build speedcubingLib
        run: |
          mvn -B package --file pom.xml


      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: speedcubingLib
          path: /target/speedcubingLib-1.0-SNAPSHOT.jar


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            artifacts: speedcubingLib
            tag: ${{ env.TAG_NAME }}
            draft: false
            prerelease: true
            releaseName: ${{ env.TAG_NAME }}
            releaseNotes: |
                ${{ env.TAG_NAME }}
                ${{ github.event.release.body }}
        
